### ISSUE TITLE
Cannot Scroll Class Methods in ValaDoc Pane

### ISSUE THREAD

**Issue by chrisdotcode** [elementaryrevivals/docs#5]
**Describe the bug**
Right under the search bar, after selecting a class, you are unable to scroll through the list of the class' methods.

**To Reproduce**
1. Open the ValaDoc view.
2. Search for a class (at this point, during the search, there is a scrollbar that you can use for just search results)
3. Select the class
4. Attempt to scroll through that class' methods with the method pane under the searchbar.
5. Cannot scroll.

**Expected behavior**
The method pane should be scrollable.

**Screenshots**
Scrollable search pane:
![image](https://user-images.githubusercontent.com/1936426/151301077-30625ae8-2ce7-4488-8574-65cc58267e4e.png)

Unscrollable method pane:
![image](https://user-images.githubusercontent.com/1936426/151300999-c313e0fd-3945-45be-aac2-507edc724ed0.png)

**System Information**
 - Distribution: elementaryOS 6.1
 - Desktop Environment: Pantheon
 - Installation Method: Flatpak (AppCenter)

**Comment by ChildishGiant** [comment]
I don't seem to be able to reproduce this issue. If there's overflow (not all methods can fit on the screen) then it will scroll. This behaviour is controlled by ValaDoc and hasn't been changed by us.


https://user-images.githubusercontent.com/13716824/152078649-741a8c52-327a-4be5-8e16-7d9f6873cab8.mp4

**Comment by chrisdotcode** [comment]
You're right: since there's no clear "end of screen" visual cue in the scroll pane, I wasn't able to immediately tell that `.remove()` was actually `Gee.HashSet`'s last method. It would be nice if ValaDoc maybe put some sort of black bar to indicate that there are no more methods, but that's not an EasyDoc issue. Thanks.
